### ISSUE TITLE
Django Front - Implementação

### ISSUE THREAD

**Issue by ZenildaVieira** [fga-eps-mds/2022-2-Squad9#101]
### Descrição
- Implementar as funcionalidades do FrontEnd no Django

### Objetivo
- Adicionar os gráficos e os dados das salas para a view do projeto

### Tarefas
- [x] Adicionar funcionalidades no FrontEnd utilizando as ferramentas do Django

### Comentários
-

**Comment by FelipeNunesdM** [comment]
Alteração da página html, e código css e exclusão de alguns arquivos que não vão ser utilizados.
