### ISSUE TITLE
GitPage - Atualização

### ISSUE THREAD

**Issue by ZenildaVieira** [fga-eps-mds/2022-2-Squad9#102]
### Descrição
- Elabora o GitPage

### Objetivo
-  Modificar o  GitPage com novas informações 

### Tarefas
- [x]  Entregar o GitPage com as novas informações 

### Comentários
-

**Comment by verabelucia** [comment]
Exemplo da GitPage:


![Captura de tela 2023-01-12 151906](https://user-images.githubusercontent.com/78658486/212147444-e037298e-67e6-478c-bc81-868c5f7b7206.png)
