### ISSUE TITLE
Instalação Metabase

### ISSUE THREAD

**Issue by raqueleucaria** [fga-eps-mds/2022-2-Squad9#11]
### Objetivo
- Introduzir de forma breve as principais funcionalidades proporcionadas pelo Metabase

### Tarefas
- Estudar o [material](https://github.com/pedrobarbosaocb/RepositorioTeste/blob/main/docs/Metabase%20-%20Getting%20Started.md) e realizar a instalação do Metabase.
- Mandar print do metabase funcionando a fim de comprovar a realização da atividade.
- Link do video de instalação: [Instalação Metabase](https://youtu.be/H5GFGJrVnqQ?t=371)

### Comentários
- Caso haja alguma dúvida a cerca do material, podem me chamar.

### Quem já fez?
- [x] Felipe
- [x] Gabriel
- [x] Edilberto
- [x] Júlia
- [x] Pedro
- [x] Raquel
- [x] Vera
- [x] Zenilda

**Comment by pedrobarbosaocb** [comment]
Link de instalação do Java atualizado!!
