### ISSUE TITLE
Docs: mapear as exceções e documentar (disciplinas/turmas)

### ISSUE THREAD

**Issue by pedrobarbosaocb** [fga-eps-mds/2022-2-Squad9#112]
### Descrição
- Listar as exceções que não serão tratadas nessa versão

### Objetivo
- Criar um documento com as disciplinas/turmas que não entraram na análise de dados dessa versão

### Tarefas
- [x] listar exceções de disciplinas/turmas
- [x] criar documento com a listagem

### Comentários
- Essas disciplinas/turmas não serão consideradas no momento por terem mais de uma sala e não ser possível determinar os horários de cada uma delas. Elas ficarão para versões futuras do projeto.

**Comment by ZenildaVieira** [comment]
Aberto o pull request, revisado pelo @pedrobarbosaocb e feito merge.
