### ISSUE TITLE
Webscrapping: alterar o dataframe para retirar exceções 

### ISSUE THREAD

**Issue by pedrobarbosaocb** [fga-eps-mds/2022-2-Squad9#113]
### Descrição
- Alteração do código de webscrapping em Python para desconsiderar as exceções que não vão ser tratadas nessa versão do projeto.

### Objetivo
- retirar do dataframe que irá alimentar o banco de dados mongoDB as disciplinas/turmas que contém duas salas ou mais, e que não é possível no momento mapear qual horário pertence a qual sala separada.

### Tarefas
- [x] refatorar o código
- [x] testar e debugar

### Comentários
- as disciplinas/turmas retiradas estão disponíveis no arquivo [Excecoes_tratamento_posterior_em_versoes_futuras.md](https://github.com/fga-eps-mds/2022-2-QuantiFGA/blob/7851190258f165d33bd11f5902beaf485e49fd89/docs/Excecoes_tratamento_posterior_em_versoes_futuras.md)

**Comment by ZenildaVieira** [comment]
Aberto o pull request, revisado pelo @pedrobarbosaocb e feito merge sem conflitos.
