### ISSUE TITLE
Testes unitários do treinamento 

### ISSUE THREAD

**Issue by pedrobarbosaocb** [fga-eps-mds/2022-2-Squad9#117]
### Descrição
- Implementação dos testes unitários em Python para o backend

### Objetivo
- Gerar testes unitários do backend do projeto utilizando o framework unittest em python

### Comentários
- há uma issue explicando a tarefa que é para ser feita aqui após o treinamento 
- ver (#99 )

### Quem já fez
- [x]  Felipe 
- [x]  Júlia
- [x]  Pedro
- [x]  Raquel
- [x]  Vera 
- [x] Zenilda

**Comment by raqueleucaria** [comment]
Realizei o teste da função separaHorario 

Foi criado uma lista de entrada com exemplos dos horários no formato coletado no sigaa e uma lista com exemplos desses horário separados corretamente.  

O teste consiste em comparar se a função retorna os valores corretos (conforme a lista de exemplos). 

O código foi implementado no PR #[136](https://github.com/fga-eps-mds/2022-2-QuantiFGA/pull/136)

**Comment by raqueleucaria** [comment]
Para rodar os testes:

1. Abra o terminal no local do arquivo dos testes
2. Escreva o seguinte comando: `python TestesUnitarios.py`

**Comment by verabelucia** [comment]
Realizei o teste da função separaSala.

Criei uma lista de entrada com exemplos das salas de acordo com os dados coletados do sigaa e outra lista para comparar com o resultado esperado.

**Comment by pedrobarbosaocb** [comment]
Realizei o teste da função getDatabase

Comparei o nome do banco de dados conectado com o que se é esperado.

**Comment by WonnzDA** [comment]
Realizei o testes das funções GerarCsv() e SalvarDados.

O teste da função SalvarDados analizou cada linha do csv de dados coletados e dados desprezados para checar se os dados foram postos no arquivos corretos.
O teste da função GerarCsv checa se os arquivos csvs foram criados e se sua estrutura interna foi gerada corretamente

**Comment by FelipeNunesdM** [comment]
Realizei o teste da função gerarConsulta() do arquivo carregarDados.py.
![image](https://user-images.githubusercontent.com/107002722/215780402-55beab9f-4c9d-482e-9b3d-fc997b412292.png)
![image](https://user-images.githubusercontent.com/107002722/215780485-15a668f2-c64d-4730-845a-ee8a9787bb1d.png)
