### ISSUE TITLE
Integração Contínua - CI - testes de integração 

### ISSUE THREAD

**Issue by pedrobarbosaocb** [fga-eps-mds/2022-2-Squad9#119]
### Descrição
- Integração frequente das diferentes branches de trabalho

### Objetivo
- Aplicar a integração contínua (CI) no projeto

### Tarefas
- [x] Criar e configurar o requerimets
- [x] Escolher uma ferramenta de CI para usar no projeto
- [x] Fazer a integração contínua 
- [x] Testar seu funcionamento

### Comentários
-

**Comment by raqueleucaria** [comment]
`pip freeze > requirement.txt `  seleciona os módulos do pyrhon e salva o arquivo txt

**Comment by raqueleucaria** [comment]
Ferramenta foi o Actions do Github. 
Para isso, dentro da pasta `.github` é preciso ter a pasta `workflows` e criar as integrações lá dentro no formato `yml`.

**Comment by raqueleucaria** [comment]
Nosso CI usa o `Flake8`

**Comment by raqueleucaria** [comment]
No futuro seria interessante criar mais CIs para verificar o projeto.
