### ISSUE TITLE
Django - Frontend

### ISSUE THREAD

**Issue by pedrobarbosaocb** [fga-eps-mds/2022-2-Squad9#121]
### Descrição
- Conclusão da parte visual do projeto

### Objetivo
- Concluir o front com o Django 

### Tarefas
- [ ] Mudar a legenda dos gráficos - No protótipo esta 2 barras, mas serão 3
- [x] Importar os filtros do metabase
- [x] Importar os gráficos do metabase

### Comentários
-

**Comment by raqueleucaria** [comment]
Devido a diminuição do escopo, a Django não será utilizada.
