### ISSUE TITLE
LocalHost - Deploy

### ISSUE THREAD

**Issue by pedrobarbosaocb** [fga-eps-mds/2022-2-Squad9#122]
### Descrição
-  O dados do metabase, no momento, só podem ser acessados de forma local. É nescessário a realização de um deploy para que esses dados possam ser acessados por todos do grupo.

### Objetivo
- Achar uma forma de dar deploy do metabase

### Tarefas
- [x]  Aplicar deploy do metabase pelo docker ou render

### Comentários
-

**Comment by verabelucia** [comment]
O problema com o local host foi resolvido.
