### ISSUE TITLE
Realizar o deploy do projeto

### ISSUE THREAD

**Issue by pedrobarbosaocb** [fga-eps-mds/2022-2-Squad9#139]
### Descrição
- O dados do metabase, no momento, só podem ser acessados de forma local. É necessário a realização de um deploy para que esses dados possam ser acessados por todos do grupo.

### Objetivo
- Encontrar um jeito de fazer o deploy do projeto

### Tarefas
- [x] Realizar o deploy.

### Comentários
-

**Comment by verabelucia** [comment]
Deploy realizado com sucesso !
http://quanti-fga-mb.sa-east-1.elasticbeanstalk.com

**Comment by verabelucia** [comment]
Encontramos um vídeo que nos ajudou a ter uma noção de como fazer o deploy. No video a unica diferença é que utiliza uma base de dados diferente do nosso projeto. (https://www.youtube.com/watch?v=Bc0eOvP85ts&t=379s)

**Comment by verabelucia** [comment]
Para subir a base de dados utilizei a documentação do metabase. (https://www.metabase.com/docs/latest/configuring-metabase/setting-up-metabase)

**Comment by verabelucia** [comment]
Deploy: http://quanti-fga-mb.sa-east-1.elasticbeanstalk.com/
