### ISSUE TITLE
Atualizar documentação - protótipo 

### ISSUE THREAD

**Issue by pedrobarbosaocb** [fga-eps-mds/2022-2-Squad9#142]
### Descrição
- Alterar o protótiipo
- Documentar o protótipo

### Objetivo
- Adaptar aos dados/gráficos que serão importados do Metabase

### Tarefas
- [x] Retirar a barra lateral
- [x] Abrir junto com a gitpage
- [x] Deixar mais limpo e adaptado ao design da gitpage
- [x] Padronização seguindo o guia de estilo

### Comentários
-

**Comment by raqueleucaria** [comment]
### Progresso atual:
- Falta acrescentar as funcionalidade
- Acrescentar o gráfico de volume de alunos
- Finalizar

![image](https://user-images.githubusercontent.com/81540491/214469380-3361b940-bca4-4679-be96-8a9e1ae8860c.png)

https://www.figma.com/file/2Jg3jwsH9OdfeZjoHk49sf/Gitpage---QuantiFGA?node-id=0%3A1&t=wTeeZ4kK1oKTU2aD-1

**Comment by raqueleucaria** [comment]
# Protótipo gitpage
![Page](https://user-images.githubusercontent.com/81540491/214680554-a8ac896e-c920-4bde-bf04-0704dc7b2b68.png)

**Comment by raqueleucaria** [comment]
# Protótipo dash
![Dash](https://user-images.githubusercontent.com/81540491/214680799-1738a598-4a85-48c1-976d-71179c2467b1.png)

**Comment by raqueleucaria** [comment]
Pasta com alguns ícones usados + fotos dos integrantes + fundo svg: https://github.com/pedrobarbosaocb/RepositorioTeste/tree/main/documenta%C3%A7%C3%A3o/Prot%C3%B3tipo/icone%20QuantiFGA

**Comment by raqueleucaria** [comment]
Vídeo com dicas e explicação: https://youtu.be/7ptgt6TcqAA

**Comment by raqueleucaria** [comment]
Link para o figma: https://www.figma.com/file/2Jg3jwsH9OdfeZjoHk49sf/Prot%C3%B3tipo-QuantiFGA?node-id=0%3A1&t=ZG645ZgsV61IQZN9-1

**Comment by raqueleucaria** [comment]
# Observação
![image](https://user-images.githubusercontent.com/81540491/214698795-2faef6da-4c4f-4848-84f3-ded2f81f6c32.png)

A ideia do botão "Sobre", "Integrantes" e "Apresentação" é quando clicar a tela scrollar/descer para a parte com as informações:

- Sobre: -> Sobre
> ![image](https://user-images.githubusercontent.com/81540491/214699399-8bf23505-01df-4dfc-a578-74c56fb57e8e.png)

- Integrantes -> Integrantes
> ![image](https://user-images.githubusercontent.com/81540491/214699465-2adc2bcb-a57b-4940-88e9-ed7210a111a0.png)

- Apresentação -> Vídeo
> ![image](https://user-images.githubusercontent.com/81540491/214699524-9a6059d1-4ee6-44c9-9a74-f8479afcd7e4.png)

**Comment by raqueleucaria** [comment]
Com as sugestões da professora o protótipo foi modificado novamente. Focando na padronização e seguindo o novo guia de estilo.

**Comment by raqueleucaria** [comment]
![Group 108](https://user-images.githubusercontent.com/81540491/215073198-45ab6cb8-7e2b-4ccb-9028-ae919b0ab3e5.png)
