### ISSUE TITLE
Revisão do repositório - Labels

### ISSUE THREAD

**Issue by pedrobarbosaocb** [fga-eps-mds/2022-2-Squad9#145]
### Descrição
- Revisar todas as issues e os labels utilizados

### Objetivo
- Incluir labels que estiverem faltando
- Criar novos labels se preciso

### Tarefas
- [x] Atualizar labels

### Comentários
-

**Comment by ZenildaVieira** [comment]
Todas as issues foram revisadas e rotuladas com os labels corretos. Labels adicionais foram criados quando necessário.
Revisor: @GabrielMS00
