### ISSUE TITLE
Estudos Orientação a Objetos

### ISSUE THREAD

**Issue by raqueleucaria** [fga-eps-mds/2022-2-Squad9#15]
### Objetivo
- aprender como funciona programação orientada a objeto

### Tarefas
- assistir os vídeos: https://www.youtube.com/watch?v=QY0Kdg83orY&t=1s
                               https://www.youtube.com/watch?v=RLVbB91A5-8&list=PLbIBj8vQhvm34qAAEEH_PdL2tMG9rz-P7

### Comentários
- Os vídeos explicam bem como funciona programação orientada a objetos

### Quem já fez?
- [x] Felipe
- [x] Gabriel
- [x] Edilberto
- [x] Júlia
- [x] Pedro
- [x] Raquel
- [x] Vera
- [x] Zenilda

**Comment by FelipeNunesdM** [comment]
Finish
