### ISSUE TITLE
Elaborar descrição da Release 2

### ISSUE THREAD

**Issue by pedrobarbosaocb** [fga-eps-mds/2022-2-Squad9#167]
### Descrição
- Elaborar a descrição da Release 2 do projeto

### Objetivo
- Preparar a descrição da release 2 com a lista das funcionalidades entregues e os artefatos realizados

### Tarefas
- [x] Descrição
- [x] Lista de funcionalidades
- [x] Lista de artefatos
- [x] Configuração
- [x] Bugs mapeados e melhorias
- [x] Software usados
- [x] Contribuidores
- [x] Vídeo explicativo da R2

**Comment by FelipeNunesdM** [comment]
# Descrição

Segunda Realease do projeto QuantiFGA, website de análise de ocupação de salas na FGA. Esta release abrange todas as funcionalidades do projeto juntamente com suas estruturas fundamentais. Com a extração de dados do portal público SIGAA acerca das disciplinas realizadas na FGA e as salas por elas ocupadas, o projeto compila de forma User Friendly o gerenciamento da capacidade das turmas/salas/disciplinas. 
Para mais informações confira o [ReadMe](https://github.com/fga-eps-mds/2022-2-QuantiFGA/blob/main/README.md), e caso deseje contribuir com o projeto acesse esse [ Guia de contribuição](https://github.com/fga-eps-mds/2022-2-QuantiFGA/blob/main/CONTRIBUTING.md).

# Funcionalidades

### Lista das funcionalidades entregues:

- [x] Webscrapping com Selenium - [backend/ColetaSigaaPublico.py](https://github.com/fga-eps-mds/2022-2-QuantiFGA/blob/main/backend/ColetaSigaaPublico.py)
- [x] Carga de dados automática no MongoDB Atlas
- [x] Atualização automática dos gráficos no Metabase
- [x] Visualização dos resultados em um [dashboard](https://fga-eps-mds.github.io/2022-2-QuantiFGA/frontend/index.html)
 
### Lista de artefatos realizados:
- [x] [GitPage](https://fga-eps-mds.github.io/2022-2-QuantiFGA/)
- [x] [StoryMap - épicos, features e histórias de usuários](https://github.com/fga-eps-mds/2022-2-QuantiFGA/blob/main/docs/Story-Mapping.md)
- [x] [Requisitos](https://github.com/fga-eps-mds/2022-2-QuantiFGA/blob/main/docs/Requisitos.md)
- [x] [ReadMe](https://github.com/fga-eps-mds/2022-2-QuantiFGA/blob/main/README.md)
- [x] [Código de conduta](https://github.com/fga-eps-mds/2022-2-QuantiFGA/blob/main/CODE_OF_CONDUCT.md)
- [x] [Guia de contribuição](https://github.com/fga-eps-mds/2022-2-QuantiFGA/blob/main/CONTRIBUTING.md)
- [x] [Política de segurança](https://github.com/fga-eps-mds/2022-2-QuantiFGA/blob/main/SECURITY.md)
- [x] [Licença](https://github.com/fga-eps-mds/2022-2-QuantiFGA/blob/main/LICENSE)
- [x] [Arquitetura](https://github.com/fga-eps-mds/2022-2-QuantiFGA/blob/main/docs/Documento-Arquitetura.md)
- [x] [Política de commit](https://github.com/fga-eps-mds/2022-2-QuantiFGA/blob/main/docs/Pol%C3%ADtica_de_commit.md)
- [x] [Protótipo de alta](https://github.com/fga-eps-mds/2022-2-QuantiFGA/blob/main/docs/Prot%C3%B3tipo.md)      

# Configuração
Deploy AWS
[Integração contínua](https://github.com/fga-eps-mds/2022-2-QuantiFGA/blob/main/.github/workflows/pythonCI.yml)
[Testes unitários](https://github.com/fga-eps-mds/2022-2-QuantiFGA/blob/main/backend/TestesUnitarios.py)
Cobertura dos testes unitários [Codecov - coverage](https://github.com/fga-eps-mds/2022-2-QuantiFGA/blob/main/backend/htmlcov/index.html)

# Bugs Mapeados (pontos de melhoria)

- [Algumas turmas não foram tratadas nessa versão](https://github.com/fga-eps-mds/2022-2-QuantiFGA/blob/main/docs/Excecoes_tratamento_posterior_em_versoes_futuras.md)
- Automatizar a análise de cobertura dos testes unitários

# Vídeo explicativo R2
- Assista [aqui](https://www.youtube.com/watch?v=aJmhTCS_M8Q&ab_channel=Juli)

# Softwares usados 

- Selenium v4.7.1
- Python v4.7.2
- MongoDB v6.0.3
- Metabase v0.45
- Visual Studio Code v1.74
- Java(TM) v18.0.2.1

# Contribuidores

- [Edilberto](https://github.com/edilbertocantuaria)
- [Felipe](https://github.com/FelipeNunesdM)
- [Gabriel](https://github.com/GabrielMS00)
- [Júlia](https://github.com/JuliaDaYo)
- [Pedro](https://github.com/pedrobarbosaocb)
- [Raquel](https://github.com/raqueleucaria)
- [Vera](https://github.com/verabelucia)
- [Zenilda](https://github.com/ZenildaVieira)

**Comment by raqueleucaria** [comment]
mudaria só o link do tópico 'Visualização dos resultados na [Gitpage](https://fga-eps-mds.github.io/2022-2-QuantiFGA/)' pro que vai direto pros gráficos: https://fga-eps-mds.github.io/2022-2-QuantiFGA/frontend/index.html

**Comment by pedrobarbosaocb** [comment]
Acho que seria interessante colocar um link que vai direto para o Dashboard

**Comment by pedrobarbosaocb** [comment]
Texto de descrição para a R2 correto. Tudo certo!
