### ISSUE TITLE
Apresentação em vídeo - R2

### ISSUE THREAD

**Issue by pedrobarbosaocb** [fga-eps-mds/2022-2-Squad9#168]
### Descrição
-  Para a entrega da Review 2 é nescessário a criação de um vídeo que demonstre o que é o projeto e como esse projeto funciona

### Objetivo
- Criar uma apresentação em vídeo do projeto QuantiFGA, mostrando a funcionalidade do site

### Tarefas
- [x] Criar um vídeo apresentando o projeto
- [x] Editar o vídeo do projeto

### Comentários
- Indecisão com a música o vídeo

**Comment by edilbertocantuaria** [comment]
Assista o vídeo da R2 [aqui](https://www.youtube.com/watch?v=aJmhTCS_M8Q&ab_channel=Juli)

**Comment by edilbertocantuaria** [comment]
Slides utilizado na apresentação do vídeo [aqui](https://www.canva.com/design/DAFZXYs00fs/OFxtJl9T6JTtxVIaM79uJg/view?utm_content=DAFZXYs00fs&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
