### ISSUE TITLE
Pesquisa de Banco de Dados (Mongo)

### ISSUE THREAD

**Issue by verabelucia** [fga-eps-mds/2022-2-Squad9#20]
### Descrição
- Estuda sobre a base de dados Mongo 
- Comparar o mongo com o SQL e verificar qual base de dados melhor se encaixa no projeto.

### Objetivo
- Ao final dos estudos escolher uma base de dados para ser utilizada.

### Tarefas
- [x] Estudar Mongo
- [x] Comparar mongo com SQL

### Comentários
- Enviar um breve resumo da tarefa realizada até o final da sprint atual.

**Comment by pedrobarbosaocb** [comment]
Finalizamos a instalação do mongoDB sem muitas complicações e conseguimos ligá-lo ao metabase, também de forma não muito complexa. 

Segue o print do database ligado ao metabase:
![image](https://user-images.githubusercontent.com/78980796/205145695-ad45a01d-363c-4c56-a242-dca5788a9655.png)
