### ISSUE TITLE
Documentação de software livre 

### ISSUE THREAD

**Issue by verabelucia** [fga-eps-mds/2022-2-Squad9#24]
### Descrição
- Realizar a documentação de software livre 

### Objetivo
- Elaborar código de conduta e Readme do projeto. 

### Tarefas
- [x] Fazer código de conduta 
- [x] Fazer o Readme.

### Comentários
- Enviar o código de conduta realizado.

**Comment by edilbertocantuaria** [comment]
O código de conduta foi escrito e já se encontra no repositório

**Comment by edilbertocantuaria** [comment]
Eu e o Felipe terminamos o readme
