### ISSUE TITLE
Determinação de Requisitos

### ISSUE THREAD

**Issue by ZenildaVieira** [fga-eps-mds/2022-2-Squad9#26]
### Descrição
- Realização do UML e do Requisitos de Software

### Objetivo
-  Criar um arquivo para o UML do projeto e todos os requisitos de software (funcionais, não funcionais, de dados e execução)

### Tarefas
- [x]  Fazer os requisitos
- [x]  Fazer o UML

### Comentários
- Arquivo UML em formato de .png e requisitos em formato .pdf

**Comment by FelipeNunesdM** [comment]
Os Requisitos foram definidos
