### ISSUE TITLE
Guia de Contribuição, Templates de Issues e Pull Request e Politica de commit

### ISSUE THREAD

**Issue by ZenildaVieira** [fga-eps-mds/2022-2-Squad9#31]
### Descrição
- Estudar os vários modelos de guias de contribuição, templates de issue e de Pull Request.

### Objetivo
- Criar o guia de contribuição, o template de issues e de Pull Request.

### Tarefas
- [x]  Guia de contribuição
- [x]  Template de issue
- [x]  Templete de Pull Request
- [x]  Política de commit

**Comment by GabrielMS00** [comment]
Criação de todos os templetes, política de commit e guia de contribuição.
