### ISSUE TITLE
Levantamento de habilidades e horários

### ISSUE THREAD

**Issue by edilbertocantuaria** [fga-eps-mds/2022-2-Squad9#5]
### Objetivo
- Realizar um levantamento de habilidades para melhor distribuição das atividades e escolher horários mais flexíveis de reuniões

### Tarefas
- [x] Preencher a lista de conhecimentos [aqui](https://docs.google.com/spreadsheets/d/1v7oUrHucBu-F1dFlwEqJssOpsJYW3c3MB8gRAC99nZs/edit?usp=sharing) 
- [x] Preencher a lista de horários disponíveis [aqui](https://docs.google.com/spreadsheets/d/1jAjYC5hAwtcNERN9OeRcxDMfQa6MZKa086HOHUZSrro/edit#gid=0)

### Comentários
- Por favor, atente-se para responder apenas no seu nome. 
- Os links também estão no teams/grupo do whatsapp

### Quem já fez?
- [x] Edilberto
- [x] Felipe
- [x] Gabriel 
- [x] Júlia
- [x] Pedro
- [x] Raquel
- [x] Vera
- [x] Zenilda

**Comment by ZenildaVieira** [comment]
Preenchi minha coluna da Lista de conhecimentos.
