### ISSUE TITLE
Metabase

### ISSUE THREAD

**Issue by ZenildaVieira** [fga-eps-mds/2022-2-Squad9#57]
### Descrição
- Verificar ferramentas básicas do metabase

### Objetivo
- Verificar se as funcionalidades do metabase atendem o escopo do projeto

### Tarefas
- [x] estudar ferramentas básicas do metabase
- [x] gerar gráfico com alguma informação relevante para o projeto como exemplo

### Comentários
-

**Comment by ZenildaVieira** [comment]
Issue aberta de forma errada

**Comment by ZenildaVieira** [comment]
Cancelada e substituida

**Comment by ZenildaVieira** [comment]
Corrigida e reaberta

**Comment by edilbertocantuaria** [comment]
Issue completa. Já conseguimos exportar os dados do mongoDB para o Metabase e gerar dashboards fixando alguns parâmetros e alternando outros. Finalmente!!
