### ISSUE TITLE
Vídeo da Apresentação da Release 1

### ISSUE THREAD

**Issue by ZenildaVieira** [fga-eps-mds/2022-2-Squad9#59]
### Descrição
- Em 10 minutos elaborar um vídeo explicando sobre o Quanti FGA.

### Objetivo
- Resumir nosso projeto e mostrar nossos entregavéis em um vídeo.

### Tarefas
- [x] Reunir para a gravação
- [x] Gravar o vídeo
- [x] Enviar no grupo do telegram

### Comentários
-

**Comment by pedrobarbosaocb** [comment]
Vídeo pronto e enviadooo!!
