### ISSUE TITLE
Preparação do BD - Horário por crédito

### ISSUE THREAD

**Issue by ZenildaVieira** [fga-eps-mds/2022-2-Squad9#60]
### Descrição
-  Separar os horários por crédito de todas as matérias 

### Objetivo
- Ter como retorno um csv com os horários separados 

### Tarefas
- [x] Fazer uma funções que separe os horários 

### Comentários

**Comment by ZenildaVieira** [comment]
Em reunião hoje com a Vera e a Julia definimos a padronização dos nomes das salas e como incluir a informação "horarioSeparado" no csv que vai alimentar o banco de dados.
Mais informações em:
[Padronizacao_Nome_Salas.md](https://github.com/fga-eps-mds/2022-2-QuantiFGA/blob/0f84d3da159ccc69dc3dc6b5dbcde63797a17780/backend/Padronizacao_Nome_Salas.md)
[Codificacao_Novas_Infos.pdf](https://github.com/fga-eps-mds/2022-2-QuantiFGA/blob/0f84d3da159ccc69dc3dc6b5dbcde63797a17780/backend/Codificacao_Novas_Infos.pdf)
Issues relacionadas
( https://github.com/fga-eps-mds/2022-2-QuantiFGA/issues/73 )

**Comment by verabelucia** [comment]
Criei duas funções, uma para separar os horarios e outra para adicionar as demais informações do csv com os horários já separados.

**Comment by verabelucia** [comment]
Foi utilizado a biblioteca regex, ela ajudou a separar os horários que estava no formato:
26T12 [DIAS DA SEMANA][TURNO][HORARIO]

Os horários separados ficou no seguinte formato:
2T1
2T2
6T1
6T2

**Comment by verabelucia** [comment]
Para entender melhor como funciona a biblioteca regex, estudei esse [ material](https://www.hashtagtreinamentos.com/regular-expressions-no-python)

**Comment by verabelucia** [comment]
Resultado final dos horários separados:

![Captura de tela 2022-12-21 204843](https://user-images.githubusercontent.com/78658486/209034992-c5812530-57aa-4382-b28b-0aa3cae4988c.png)
