### ISSUE TITLE
Ambientação do parser - Selenium para MongoDB (Django)

### ISSUE THREAD

**Issue by ZenildaVieira** [fga-eps-mds/2022-2-Squad9#64]
### Descrição
- Gerando a ligação do Selenium com o MongoDB por meio do Django.

### Objetivo
- Automatizar a passagem de informação do Selenium para o banco de dados .

### Tarefas
- [x] Estudar e instalar o Django corretamente.
- [x]  Demonstrar Django funcionando corretamente.
- [ ] ~Gerar um código inicial do Django aplicado ao nosso projeto~
---
### Comentários
- É necessário comprovar realização das tarefas.

**Comment by pedrobarbosaocb** [comment]
Código inicial gerado
---
![image](https://user-images.githubusercontent.com/78980796/209396299-1663916e-fad2-4729-a971-47b57246ba90.png)
