### ISSUE TITLE
Ambientação da conexão do MongoDB com o Frontend (Django)

### ISSUE THREAD

**Issue by ZenildaVieira** [fga-eps-mds/2022-2-Squad9#66]
### Descrição
- Gerando a ligação do MongoDB com o Front por meio do Django.

### Objetivo
- Iniciar o ambiente Django e estudar sobre essa tecnologia.

### Tarefas
- [x] Gerar um código inicial do Django .

> Comprovar a geração do código inicial.

### Comentários
-

**Comment by FelipeNunesdM** [comment]
Consegui fazer um exemplo da página com Django!

![image](https://user-images.githubusercontent.com/107002722/209410873-60fc8988-9d19-4459-b5f1-4c342becc726.png)
