### ISSUE TITLE
Metodologia Scrum

### ISSUE THREAD

**Issue by WonnzDA** [fga-eps-mds/2022-2-Squad9#7]
### Objetivo
- Passar o conhecimento da metodologia Scrum de forma simples

### Tarefas
- [x] Ler o resumo

### Comentários
- Qualquer dúvida pode mandar mensagem

![scrum graph](https://user-images.githubusercontent.com/112433653/202877221-818ebde5-9593-4190-999a-08db6a0911f8.png)

### Quem já fez?
- [x] Edilberto
- [x] Felipe
- [x] Gabriel
- [x] Júlia
- [x] Pedro
- [x] Raquel
- [x] Vera
- [x] Zenilda

**Comment by ZenildaVieira** [comment]
Tarefa realizada por mim - resumo lido.

**Comment by edilbertocantuaria** [comment]
Tarefa realizada por mim - resumo lido.
