### ISSUE TITLE
Metabase - treinamento básico

### ISSUE THREAD

**Issue by ZenildaVieira** [fga-eps-mds/2022-2-Squad9#85]
### Descrição
- Treinamento do grupo de como utilizar as principais ferramentas do Metabase.
- Assistir ao vídeo do treinamento: [Clique aqui](https://youtu.be/9xb4Tsr7pZg)

### Objetivo
- Instruir como utilizar o Metabase com os dados do Mongo DB: como filtrar informações, gerar gráficos e realizar o embeded 

### Tarefas
- [ ] Gravar um vídeo e disponibilizar (Assignee - Edilberto) 
- [ ] Gerar dois gráficos do metabase: um que tem horário fixo (ou seja, faz uma varredura de todas as salas que tem aquele horário) e outro que tem uma disciplina específica (ou seja, mostra quais salas e horários tem aquela disciplina). Deixar prints aqui no comentário

### Quem já fez?
- [x] Felipe
- [ ] Gabriel
- [x] Edilberto
- [x] Júlia
- [ ] Pedro
- [ ] Raquel
- [ ] Vera
- [x] Zenilda

**Comment by WonnzDA** [comment]
O vídeo cumpre o papel descrito na issue de forma clara e compreensiva

**Comment by FelipeNunesdM** [comment]
![image](https://user-images.githubusercontent.com/107002722/212492982-2da66c23-121d-4b76-8469-7ea49a40e43b.png)

**Comment by WonnzDA** [comment]
- Aplicação do que foi passado no vídeo
![metabase_dashboard](https://user-images.githubusercontent.com/112433653/212894230-525e854d-4ef8-467e-8b14-3f8fc2c1a133.png)
