### ISSUE TITLE
Django - instalação e treinamento básico

### ISSUE THREAD

**Issue by ZenildaVieira** [fga-eps-mds/2022-2-Squad9#86]
### Descrição
- Treinamento básico de Django para todo o grupo

### Objetivo
- Guiar o grupo pelos primeiros passos com Django

### Tarefas
- [ ] Definir forma de treinamento
- [ ] Definir tarefas para comprovar a realização do treinamento

### Quem já fez?
- [ ] Felipe
- [ ] Gabriel
- [ ] Edilberto
- [x] Júlia
- [x] Pedro
- [ ] Raquel
- [ ] Vera
- [x] Zenilda

**Comment by pedrobarbosaocb** [comment]
# Atividade Obrigatória

Ler e aplicar a primeira página desse tutorial:
>https://docs.djangoproject.com/pt-br/4.1/intro/tutorial01/

    Com isso você terá um projeto básico e inicial em Django para você se aventurar e explorar mais a ferramenta

# Atividade Opicional
Realizar o tutorial por completo.

    Com isso você terá uma base de conhecimento forte facilitando a utilização do django em vários contextos.

**Comment by ZenildaVieira** [comment]
Revisão do treinamento feita. Instalação e treinamento satisfatórios para o básico.

![image](https://user-images.githubusercontent.com/101183963/211689043-090435b2-8d92-439b-a74e-6230e9b4215b.png)

![image](https://user-images.githubusercontent.com/101183963/211688974-7c30b07e-d00f-44e8-89e1-6ba5232088d6.png)
