### ISSUE TITLE
Django - código inicial FrontEnd

### ISSUE THREAD

**Issue by ZenildaVieira** [fga-eps-mds/2022-2-Squad9#88]
### Descrição
- Conectar o Django com o FrontEnd

### Objetivo
- Implementar o FrontEnd do projeto no código Python Django

### Tarefas
- [x] Replicar o FrontEnd no Django
- [x] Encaixar os códigos aos códigos já presentes no projeto a fim de não possuir conflitos

### Comentários
-

**Comment by FelipeNunesdM** [comment]
https://user-images.githubusercontent.com/107002722/211652084-ea2ea3f8-1593-4ee4-9199-e17c2ce871b9.mp4

**Comment by pedrobarbosaocb** [comment]
A issue compriu o objetivo proposto! @FelipeNunesdM já pode fechá-la.
