### ISSUE TITLE
Atualização do protótipo de alta

### ISSUE THREAD

**Issue by ZenildaVieira** [fga-eps-mds/2022-2-Squad9#89]
### Descrição
- Protótipo de alta fidelidade conforme as mudanças do projeto.

### Objetivo
- Recriar um protótipo no figma, reduzindo o escopo do projeto, além de aproveitar mais a área da página. Separar os espaços que receberão os gráficos do metabase, etc.

### Tarefas
- [x] Liberar mais espaço para alocar as informações
- [x] Reduzir o escopo
- [x] Deixar uma área para os gráficos
- [x] Melhorar no geral o protótipo

# Protótipo criado:
- Link do figma: https://www.figma.com/file/m1f4pgZokcUvx6vQ0PYrhc/Prototipo---QuantiFGA?node-id=0%3A1&t=1uk69pAM6S8ZCGQx-1 
![png](https://raw.githubusercontent.com/pedrobarbosaocb/RepositorioTeste/main/documenta%C3%A7%C3%A3o/Prototipo2.png)

**Comment by raqueleucaria** [comment]
Protótipo concluido, enviado para revisão.
