### ISSUE TITLE
Atualização do story map

### ISSUE THREAD

**Issue by ZenildaVieira** [fga-eps-mds/2022-2-Squad9#90]
### Descrição
- Fazer a atualização do story map do projeto.

### Objetivo
- Substituir o sotry map atual por um que esteja atualizado e de acordo com o software que estamos desenvolvendo.

### Tarefas
- [x] Criar o novo story map

**Comment by GabrielMS00** [comment]
Story Map atualizado de acordo com o novo protótipo de alta fidelidade.
