### ISSUE TITLE
Definição de gráficos do metabase

### ISSUE THREAD

**Issue by ZenildaVieira** [fga-eps-mds/2022-2-Squad9#91]
### Descrição
- Analisar gráficos  para o projeto 

### Objetivo
- Analisar os gráficos e definir os tipos que melhor se encaixa com o projeto 

### Tarefas
- [x] Analisar os gráficos 
- [x] Escolher os gráficos para o projeto 

### Comentários
-

**Comment by verabelucia** [comment]
Os gráficos de comparação pode ser usados para comparar um os mais conjunto de dados. Eles podem comparar itens  ou mostrar as diferenças. Podemos criar gráficos de comparação com o total de vagas ofertadas e o total de vagas ocupadas.
Exemplo: 
![tipos-de-graficos-matematica](https://user-images.githubusercontent.com/78658486/211915947-ad3e3665-d3e0-4791-9d66-6dc4a8ff096c.jpeg)

**Comment by verabelucia** [comment]
Os gráficos de pizza representam números em porcentagem e a soma total de todos os segmentos do gráficos. Com esse gráfico podemos comparar a lotação total das salas com a quantidade de vagas oferecidas e a quantidade de vagas ocupadas.
![grafico-pizza-cke](https://user-images.githubusercontent.com/78658486/211918665-818cbd28-6c87-4ca6-a9b3-e5a0cfee6baa.jpg)

**Comment by GabrielMS00** [comment]
Gostei da escolha dos gráficos, são de fácil interpretação, ao mesmo tempo vão conseguir mostrar bem todos os dados que precisamos ofertar aos usuários do nosso sistema; podemos seguir com essa escolha e partir para a implementação.
